### ISSUE TITLE
您好，请教一下rem的适配

### ISSUE THREAD

**Issue by Yaob1990** [reming0227/atom-design#2]
我看您代码里面是用的px单位
那我如果使用的时候，需要用postcss把px转成rem单位吗？

多谢。也在想写一个公司内部的组件库，不知道单位我是应该用px还是rem。

**Comment by fwm227** [comment]
写组件就用px去做吧，px to rem现在并不适合做自适应，px to viewport兼容已经很好了


------------------ 原始邮件 ------------------
发件人: "Yao"<notifications@github.com>;
发送时间: 2019年9月1日(星期天) 晚上9:33
收件人: "reming0227/atom-design"<atom-design@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [reming0227/atom-design] 您好，请教一下rem的适配 (#2)




我看您代码里面是用的px单位
 那我如果使用的时候，需要用postcss把px转成rem单位吗？
 
多谢。也在想写一个公司内部的组件库，不知道单位我是应该用px还是rem。

**Comment by Yaob1990** [comment]
哇，好快的回复。
这么友好的项目，我要仔细阅读您的源码，和您多多请教。
