### ISSUE TITLE
请问下文档的源码在哪里呢？

### ISSUE THREAD

**Issue by Yaob1990** [reming0227/atom-design#3]
好像没有看到文档的源码，有时候上网不方便，希望可以本地运行。

还想再请教个问题，我看到源码里面大部分的结构是使用的render生成的，这里为什么不写成模板的形式呢。平时工作中，render我用的非常少，不了解。求解答。

**Comment by fwm227** [comment]
文档源码地址：https://github.com/atom-design/docs

模板可读性确实更好一点，模板写法最后也是通过插件(vue-template-compiler)编译为render，我用render只是想通过更接近底层的方式来实现组件

**Comment by Yaob1990** [comment]
感谢~
