### ISSUE TITLE
radio 里面的 watch  disabled 函数作用

### ISSUE THREAD

**Issue by Yaob1990** [reming0227/atom-design#4]
![image](https://user-images.githubusercontent.com/22534346/64597123-bdfea880-d3e7-11e9-8e00-f6d62b015547.png)

这个监听，好像没有必要？我注释掉，好像没有影响，请教一下，是我哪里没有想到。

**Comment by fwm227** [comment]
感谢支持，这个是当disabled设置为true时开启禁用才会有效果的

**Comment by fwm227** [comment]
若是发现有代码需要改进欢迎提PR

**Comment by Yaob1990** [comment]
感谢感谢~
